/*DELIMITADOR DE COMANDOS (PONTO E VIRGULA ;)

/*ALTERANDO O DELIMITADOR*/
DELIMITER $;

/*ESQUECI O DELIMITADOR QUE ESTOU USANDO -> UTILIZO O COMANDO STATUS*/

/*status verifico a saude do servidor*/
STATUS
