/*FUNCOES DE AGREGACAO NUMERICAS */

CREATE TABLE vendedores(
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(30),
sexo ENUM('M','F'),
janeiro FLOAT(10,2),
fevereiro FLOAT(10,2),
marco FLOAT (10,2)
);

INSERT INTO VENDEDORES VALUES (NULL, 'Joana', 'F', 30013.44, 2366.33, 4367.12);
INSERT INTO VENDEDORES VALUES (NULL, 'Mauricio', 'M', 400500.00, 30024.23, 80023.42);
INSERT INTO VENDEDORES VALUES (NULL, 'Washington', 'M', 600.00, 1800.23, 5000.42);
INSERT INTO VENDEDORES VALUES (NULL, 'Cleber', 'M', 500500.00, 50024.23, 10023.42);
INSERT INTO VENDEDORES VALUES (NULL, 'Fernanda', 'F', 400500.00, 30024.23, 80023.42);
INSERT INTO VENDEDORES VALUES (NULL, 'Jonnathan', 'M', 700500.00, 90024.23, 19623.42);
INSERT INTO VENDEDORES VALUES (NULL, 'Condorna', 'F', 400.00, 900.23, 1000.42);
INSERT INTO VENDEDORES VALUES (NULL, 'Rogerio', 'M', 90000.00, 60024.23, 70023.42);
INSERT INTO VENDEDORES VALUES (NULL, 'Liria', 'F', 990300.65, 70623.13, 38023.12);

/*MAX TRAZ O  VALOR MAXIMO DE UMA COLUNA*/

SELECT MAX(FEVEREIRO) AS 'MAIOR VALOR DE VENDAS FEVEREIRO' FROM vendedores;

/*Min TRAZ O  VALOR MINIMO DE UMA COLUNA*/

SELECT MIN(FEVEREIRO) AS 'VALOR MINIMO DE VENDAS DO MES DE FEV' FROM vendedores;

/*avg tras o valor medio de uma coluna*/

SELECT AVG(MARCO) AS 'VALOR MEDIO DA COLUNA DE MARCO' FROM vendedores;

/*varias funcoeos*/
/*TRUNCATE TRUNCA OS VALORES */

SELECT MIN(JANEIRO) AS 'MIN_JAN',
       MAX(FEVEREIRO) AS 'MAX_FEV',
       TRUNCATE(AVG(MARCO),2) AS 'MED_MAR'/*FUNCAO PEDE 2 PARAMETROS 1 O NUMERO O 2 A QTD DE CASA DECIMAIS QUE QUERO NESSE NÚMERO*/
       FROM VENDEDORES;
/*Agregando com o SUM = soma todas as linhas da coluna selecionada*/

SELECT SUM(JANEIRO) AS 'MAX_JAN' FROM vendedores;

SELECT sexo,SUM(marco) AS 'MAX_MAR'
FROM vendedores
GROUP BY sexo;


/*SUBQUERYS UMA QUERY DENTRO DE OUTRA QUERY*/
/*Vendedor que vendeu menos no mes de março e seu nome*/

SELECT nome, marco
FROM vendedores
WHERE marco = (SELECT MIN(marco) FROM vendedores);

/*NOME E O VALOR DE QUEM VENDEU MAIS EM MARÇO*/

SELECT nome, marco
FROM vendedores
WHERE marco = (SELECT MAX(MARCO) FROM VENDEDORES) ORDER BY NOME;

/*QUEM VENDEU MAIS QUE O VALOR MEDIO DE FEVEREIRO*/
SELECT NOME, FEVEREIRO
FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES); /*A QUERY DE DENTRO CHAMA-SE INNER QUERY QUERY DE DENTRO */
