/*Alterando as Tabelas*/
CREATE TABLE TABELA(
COLUNA1 VARCHAR(30),
COLUNA2 VARCHAR(30),
COLUNA3 VARCHAR(30)
);

/*Adicionando uma chave primaria PK*/

ALTER TABLE TABELA
ADD PRIMARY KEY (COLUNA1);

/*lembrando desc tabela descreve a coluna*/
DESC tabela;

/*obs não tenho como dar AUTO_INCREMENT inserindo por fora*/

/*ADICIONANDO UMA COLUNA*/
ALTER TABLE tabela
ADD coluna VARCHAR(30);

/*ADICIONANDO UMA COLUNA COM POSICAO*/
ALTER TABLE TABELA
ADD COLUNA4 VARCHAR(30) NOT NULL UNIQUE
AFTER COLUNA3;

/*OBS AS ALTERAÇÕES REALIZADAS NAS TABELAS TEM QUE SER COMPATIVEIS COM OS DADOS DO CAMPO QUE ESTOU UTILIZANDO
EX: TENHO DADOS INTEIRO E QUERO MUDAR O TIPO PARA VARCHAR VAI DAR ERRO OU OS TIPOS DEVEM SER COMPATIVEIS PARA MUDAR
EX: VARCHAR 30, 40, 50, 60 (NA TABELA) POSSO ALTERAR PARA INT*/

/*MODIFICANDO O TIPO DO CAMPO*/
ALTER TABLE TABELA
MODIFY COLUNA2 DATE NOT NULL;

/*RENOMEANDO O NOME DA TABELA*/
ALTER TABLE TABELA
RENAME PESSOA;

CREATE TABLE TIME (
ID INT PRIMARY KEY NOT NULL,
TIME VARCHAR(30),
ID_PESSOA VARCHAR(30)
);

ALTER TABLE TIME
ADD FOREIGN KEY(ID_PESSOA)
REFERENCES PESSOA(COLUNA1);

/*VERIFICAR AS CHAVES*/
SHOW CREATE TABLE TIME;

show create table jogador;
show create table times;

