/*Auto-relacionamento tabela que se relaciona com ela mesmo*/

CREATE TABLE CURSOS(
IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR(30),
HORAS INT,
VALOR FLOAT (10,2),
ID_PREREQ INT
);

ALTER TABLE CURSOS ADD CONSTRAINT FK_PREREQ
FOREIGN KEY (ID_PREREQ) REFERENCES CURSOS (IDCURSO);

INSERT INTO CURSOS VALUE(NULL, 'BD RELACIONAL', 20, 400.00, NULL);
INSERT INTO CURSOS VALUE(NULL, 'BUSINESS INTELIGENCE', 40, 800.00, 1);
INSERT INTO CURSOS VALUE(NULL, 'Relatorios Avancados', 20, 600.00, 2);
INSERT INTO CURSOS VALUE(NULL, 'Logica Program', 20, 400.00, NULL);
INSERT INTO CURSOS VALUE(NULL, 'RUBY', 20, 400.00, NULL);

select nome,horas,valor,ifnull(id_prereq,"Sem prerequisitos") from cursos;

SELECT
C.NOME AS 'CURSO',
C.VALOR AS 'VALOR',
C.HORAS AS 'CARGA HORARIA',
IFNULL(P.NOME , "-----") AS 'PREREQUISITO'
FROM CURSOS C
INNER JOIN CURSOS P /*INNER JOIN INTERSECÇÃO DE */
ON P.IDCURSO = C.ID_PREREQ;

SELECT
C.NOME AS 'CURSO',
C.VALOR AS 'VALOR',
C.HORAS AS 'CARGA HORARIA',
IFNULL(P.NOME , "-----") AS 'PREREQUISITO'
FROM CURSOS C
left JOIN CURSOS P /*Apenas dados do conjunto da esquerda */
ON P.IDCURSO = C.ID_PREREQ;
