SELECT CO.ID_CONTA, CO.NR_DIGITO_CONTA, CO.VL_SALDO, BA.NM_BANCO, AG.NM_AGENCIA, TP.NM_TIPO_CONTA
FROM TAB_CONTA CO
INNER JOIN TAB_BANCO BA ON CO.ID_BANCO = BA.ID_BANCO
INNER JOIN TAB_BANCO_AGENCIA AG
           ON CO.ID_BANCO = AG.ID_BANCO AND
              CO.ID_AGENCIA = AG.ID_AGENCIA
INNER JOIN TAB_CORRENTISTA CR ON CR.ID_CORRENTISTA = CO.ID_CORRENTISTA
INNER JOIN TAB_TIPO_CONTA TP ON CO.ID_TIPO_CONTA = TP.ID_TIPO_CONTA
WHERE CR.NM_NOME = 'ADALTON ISIDORO';


select * from TAB_correntista where NM_NOME like '%ADALTON%';